### ISSUE TITLE
2015.3.30 issue

### ISSUE THREAD

**Issue by zhanglei1949** [sjtu-XutongLu/NumGuess#2]
1.第86行的输出建议修改将三个数字隔开；
2.A和B的计数可以更简洁。
2.表示代码好高端。
3.注释也很清晰。

**Comment by LycorisXu** [comment]
Your code is quite good, almost every line is necessary. But i think a, b, c and input_a , input_c, input_c can be replaced by two array to make it succinct.

**Comment by cpxdudu** [comment]
1、程序顺利运行，且有输入检查
2、注释清晰，程序格式整齐
3、同样觉得代码好高端，膜拜
